name: task_manager
description: >
  Application CLI de gestion de tâches en Dart pur.
  Architecture en couches, persistance JSON, héritage Task → UrgentTask,
  interfaces, génériques Repository<T> et exceptions personnalisées.
version: 1.0.0
repository: https://github.com/Eliezozo/task-manager-dart

environment:
  sdk: ^3.12.2

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
